#cloud-config
apt_upgrade: True
apt_reboot_if_required: False
runcmd:
  - fallocate -l 4G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab;
  - /usr/bin/docker run -d -p 80:80 sagikazarmark/dvwa
  - ufw disable
  - apt install -y mosh atop net-tools docker-compose
  - git clone --recursive -q "https://github.com/srnfr/vpp-lab.git" /home/vpplab
  ## Dive
  - wget https://github.com/wagoodman/dive/releases/download/v0.12.0/dive_0.12.0_linux_arm64.deb
  - apt install ./dive_0.12.0_linux_arm64.deb
  ## Grype
  - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
  ## xpid
  - curl -sSfL https://raw.githubusercontent.com/srnfr/do-droplet-terraform/main/install-xpid.sh | sh -s -- -b /usr/local/bin
  ## ndots
  - rm -f /etc/resolv.conf ; echo "nameserver 1.1.1.1" > /etc/resolv.conf ; echo "options ndots:5" >> /etc/resolv.conf
##  - /bin/sh /home/vpplab/prepare.sh
  ## install docker sbom
  - curl -sSfL https://raw.githubusercontent.com/docker/sbom-cli-plugin/main/install.sh | sh -s --
snap:
    commands:
        00: ['install', 'yq']
