#cloud-config
disk_setup:
    ephemeral0:
        table_type: mbr
        layout: [90, [9, 82]]
        overwrite: True
fs_setup:
    - device: ephemeral0.1
      filesystem: ext4
    - device: ephemeral0.2
      filesystem: swap
mounts:
    - ["ephemeral0.1", "/mnt"]
    - ["ephemeral0.2", "none", "swap", "sw", "0", "0"]
runcmd:
  - /usr/bin/docker run -d -p 80:80 sagikazarmark/dvwa
  - ufw disable
  - apt update && apt install -y mosh atop
  - git clone --recursive -q "https://github.com/srnfr/vpp-lab.git" /home/vpplab
  - /bin/sh /home/vpplab/prepare.sh
snap:
    commands:
        00: ['install', 'yq']
